Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,6 +12,12 @@ on:
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
+    inputs:
+        suite:
+          required: true
+          type: string
+          description: Enter the dev branch to deploye on Automation Env
+          default: E2E
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -24,6 +30,20 @@ jobs:
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
+
+      - name: Check if branch exists
+        id: check_branch
+        run: |
+          BRANCH="${{ github.event.inputs.branch }}"
+          echo "Checking for branch: $BRANCH"
+          
+          if git ls-remote --heads origin "$BRANCH" | grep -q "$BRANCH"; then
+            echo "Branch exists"
+          else
+            echo "❌ Branch '$BRANCH' not found on remote."
+            echo "Cancelling workflow."
+            exit 1
+          fi
 
       # Runs a single command using the runners shell
       - name: Trigger TestGithubActions Pipeline
